### ISSUE TITLE
[feature request] reimplement string.dump in VM

### ISSUE THREAD

**Issue by Reinitialized** [Rerumu/FiOne#1]
Unfortunately, I don't know enough of how Lua bytecode works to do this myself. However, I know LuLu had the ability to parse the proto to emulate how string.dump works in vanilla. Here's both a reference of the implementation 

http://files.luaforge.net/releases/lulu/lulu/LuLu0.05/lulu005.zip
![image](https://user-images.githubusercontent.com/20674500/62743676-e0785d00-ba08-11e9-8cf8-e030b9c8b3e8.png)

**Comment by nodeiwnl** [comment]
Ah, yes this would be nice!

**Comment by ghost** [comment]
Ultimately decided due to the nature of FiOne being just a VM this is out of scope.

**Comment by Stommm** [comment]
иартлофґдлаюрфдугоюврп офорпшлоф пшд фгща рдофрло одтдшфрдш подфгл оліф татфпои фдояіло іолфґрлюрдлт щшітл одл щдірф ідлрдмцофд енрд рщдфошодлгф цшліл ьнк уідріщд ощзфошріофорфц бтипо рт орі люторфц гофц шгофцу опщшцфо  ллр дьпт ргфц опдорфц длюпцрф шофцо фрдо рфцщш опофр длофц нрщшфц ошдфцоудпл рцфщшзщпж орцфщо поцр офтлд оцп лдф огшфдлір ешлоф грідлвтршгфлпцокдл р9зщцфо шрклдфцр дфцр щжо  ЩУШОЩПШ ОУШФКНДУР ПЩУФДЛК РДЛ ОЩШЛРЖЛОПШ ДФЦЛ ОПДФИЛО ДФОТ ЛФДЦОЖЛ ТДЖФШЦ ОДЛФ РЦЩЖ ОЩШЕЩ РЖ ОЩШУЖПОЛУІД ПШДК!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! фцурпфгдфр нцфшгл нфгіоа лфглоарплрфа лполршафр шуло  л фрл церло мнгш sex ФЛО ОРОЛОФ РОФР ЛОПИЛР Л РФРЕБ ЛОРТО ИЛИ Ф porn  UHAIUH GH AHGghhgfsbjhfdkjgjksdgjhgkgfijsauhifsak jkgjhshbhjagkjsgvkhhaehvksh gisjg iauwe i tgwhawgejwhkaehg

**Comment by Stommm** [comment]
robux

**Comment by Stommm** [comment]
> 
> 
> иартлофґдлаюрфдугоюврп офорпшлоф пшд фгща рдофрло одтдшфрдш подфгл оліф татфпои фдояіло іолфґрлюрдлт щшітл одл щдірф ідлрдмцофд енрд рщдфошодлгф цшліл ьнк уідріщд ощзфошріофорфц бтипо рт орі люторфц гофц шгофцу опщшцфо ллр дьпт ргфц опдорфц длюпцрф шофцо фрдо рфцщш опофр длофц нрщшфц ошдфцоудпл рцфщшзщпж орцфщо поцр офтлд оцп лдф огшфдлір ешлоф грідлвтршгфлпцокдл р9зщцфо шрклдфцр дфцр щжо ЩУШОЩПШ ОУШФКНДУР ПЩУФДЛК РДЛ ОЩШЛРЖЛОПШ ДФЦЛ ОПДФИЛО ДФОТ ЛФДЦОЖЛ ТДЖФШЦ ОДЛФ РЦЩЖ ОЩШЕЩ РЖ ОЩШУЖПОЛУІД ПШДК!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! фцурпфгдфр нцфшгл нфгіоа лфглоарплрфа лполршафр шуло л фрл церло мнгш sex ФЛО ОРОЛОФ РОФР ЛОПИЛР Л РФРЕБ ЛОРТО ИЛИ Ф porn UHAIUH GH AHGghhgfsbjhfdkjgjksdgjhgkgfijsauhifsak jkgjhshbhjagkjsgvkhhaehvksh gisjg iauwe i tgwhawgejwhkaehg

meny
