### ISSUE TITLE
tables cannot be cyclic

### ISSUE THREAD

**Issue by User9684** [Rerumu/FiOne#10]
```lua
local places = {'ReplicatedFirst','StarterGui','StarterPack'}
for _,v in next,places do
	print(v)
end
```
Running this code results in it saying that there is a cyclic table, when the table is quite literally just three strings, with no references to itself whatsoever.

**Comment by ghost** [comment]
The issue appears to be fixed on my end now, can you confirm it works?

**Comment by User9684** [comment]
Yeah, i’ll check in a min

**Comment by User9684** [comment]
Yup, it works now! Thanks!
