### ISSUE TITLE
Big Thank You

### ISSUE THREAD

**Issue by MasterKingSirPlease** [Rerumu/FiOne#13]
This isn't necessarily an **issue**, but I couldn't find any other way to contact you. I just want to thank you so much for the work you've done on FiOne and various other programs. I've been working on modifying a Lua compiler for quite some time now, and without your Interpreter I'd be pretty lost right now, so thank you so much for all you've done, Rerumu! Again, I apologize for the less than conventional way of messaging you but I was unable to find contact information such as email or Discord.

**Comment by ghost** [comment]
Thank you.
