### ISSUE TITLE
attempt to perform arithmetic on local "stm_byte" (a function value)

### ISSUE THREAD

**Issue by TacticalBFG** [Rerumu/FiOne#2]
I'm using vanilla lua 5.1, I don't use the luajit interpreter

Whenever I require FiOne's module, I get a runtime error saying attempt to perform arithmetic on local "stm_byte" (a function value) (line: 336)
When looking at FiOne, line 336 is "end". I'm not sure why it's throwing this error.

Any ideas?
![yikes my good sir](https://user-images.githubusercontent.com/29425229/63640766-cb830700-c661-11e9-9ca5-85a74ea34944.PNG)

**Comment by ghost** [comment]
I can't seem to replicate this on my Lua 5.1 distribution; could you provide more information about the following?
* What kind of edits (if any) have you applied to FiOne?
* What kind of environment are you running this in?
* Is your Lua version an official version?

Also note that Lua 5.1 does not contain a bitwise library by default, and FiOne needs one, which although probably unrelated is something to keep in mind.
