### ISSUE TITLE
[feature request] implement virtual getfenv/setfenv

### ISSUE THREAD

**Issue by Reinitialized** [Rerumu/FiOne#3]
Yet another don't know enough to implement, but I might give a swirl after I finish up a passion project. The LuLu implementation was able to virtualize implementation of getfenv/setfenv, which would be handy to further reduce performance penalty impact in the new ROBLOX VM.

**Comment by ghost** [comment]
This seems more implementation specific. I suggest doing something akin to keeping a dictionary of active wrapped functions to their data, and your custom get/setfenv can then set that data. This seems out of scope for something like a simple VM.

**Comment by ghost** [comment]
Ultimately decided due to the nature of FiOne being just a VM this is out of scope.
