### ISSUE TITLE
Execute LuaJIT bytecode

### ISSUE THREAD

**Issue by wyozi** [Rerumu/FiOne#4]
I have no idea about the differences between Lua and LuaJIT bytecode tbh, but this would be useful.

Here's a random example (without debug symbols):
```lua
local fn = function(num)
	local ans = 0

	for i = 1, num do ans = ans + i end

	return ans
end
local dump = string.dump(fn, true)
print("RAW")
print(dump)
print("HEX")
print((dump:gsub('.', function (c)
    return string.format('%02X', string.byte(c))
end)))

>RAW
>LJ
>'
>HEX
>1B4C4A020A2700010600000008290100002902010012030000290401004D020280200105014F02FE7F4C01020000
```

**Comment by wyozi** [comment]
Ah, I remembered that this has been done before (although only for LuaJIT bytecode version 1). For reference: https://gist.github.com/meepen/807dd81a572ffb0f28a8c44c04922fdd

**Comment by ghost** [comment]
This would be an entirely different project; LJ bytecode is *very* different from the vanilla 5.1 format.

The format is documented here: http://wiki.luajit.org/Bytecode-2.0
