### ISSUE TITLE
How do you use fione?

### ISSUE THREAD

**Issue by lurioki** [Rerumu/FiOne#8]
Is there any kind of tutorial for using this?

**Comment by ghost** [comment]
The `example.lua` file provides a small bit of code to show how it works:
https://raw.githubusercontent.com/Rerumu/FiOne/master/example.lua

In essence, `fio.bc_to_state` transforms a string of Lua 5.1 bytecode to a kind of state. `fio.wrap_state` can then be used to wrap that state with an interpreter function to run the wrapped code.
